uav1:
  id: 1
  x: -1.0
  y: 2.0
  z: 0.5
  heading: 1.57079

uav2:
  id: 2
  x: -3.0 
  y: -2.0
  z: 0.5
  heading: 1.57079

uav3:
  id: 3
  x: 1.0 
  y: -2.0
  z: 0.5
  heading: 1.57079

####################################################################################
############################### BIG MAZE ###########################################
####################################################################################
# 1st layout -> Joint Start 1
#uav1:
#  id: 1
#  x: 0.0
#  y: 0.0
#  z: 0.5
#  heading: 3.14159

#uav2:
#  id: 2
#  x: 0.0 
#  y: 2.0
#  z: 0.5
#  heading: 3.14159

#uav3:
#  id: 3
#  x: 0.0 
#  y: 4.0
#  z: 0.5
#  heading: 3.14159

####################################################################################
################################### MAZE ###########################################
####################################################################################
# 1st layout -> Joint Start 1
#uav1:
#  id: 1
#  x: 8.5 
#  y: 7.5
#  z: 0.5
#  heading: 3.14159

#uav2:
#  id: 2
#  x: 0.0 
#  y: 7.5
#  z: 0.5
#  heading: 3.14159

#uav3:
#  id: 3
#  x: -8.5 
#  y: 7.5
#  z: 0.5
#  heading: -1.57079

# 2nd layout -> Separated Start 1
#uav1:
#  id: 1
#  x: 8.5 
#  y: 7.5
#  z: 0.5
#  heading: 3.14159

#uav2:
#  id: 2
#  x: 8.5 
#  y: 4.0
#  z: 0.5
#  heading: 1.57079

#uav3:
#  id: 3
#  x: -8.5 
#  y: -7.5
#  z: 0.5
#  heading: 0.0

####################################################################################
############################ POLICE STATION ########################################
####################################################################################
# 1st layout -> Joint Start 1
#uav1:
#  id: 1
#  x: -12
#  y: 0
#  z: 0.5
#  heading: 0

#uav2:
#  id: 2
#  x: -12
#  y: 4
#  z: 0.5
#  heading: 0

#uav3:
#  id: 3
#  x: -12
#  y: -4
#  z: 0.5
#  heading: 0

# 2st layout -> Joint Start 2
#uav1:
#  id: 1
#  x: 12 
#  y: 0
#  z: 0.5
#  heading: 3.14159

#uav2:
#  id: 2
#  x: 12
#  y: 4
#  z: 0.5
#  heading: 3.14159

#uav3:
#  id: 3
#  x: 12
#  y: -4
#  z: 0.5
#  heading: 3.14159

# 3rd layout -> Joint Start 3
#uav1:
#  id: 1
#  x: 0 
#  y: -13.5
#  z: 0.5
#  heading: 1.57079

#uav2:
#  id: 2
#  x: 4
#  y: -13.5
#  z: 0.5
#  heading: 1.57079

#uav3:
#  id: 3
#  x: -4
#  y: -13.5
#  z: 0.5
#  heading: 1.57079

# 4th layout -> Joint Start 4
#uav1:
#  id: 1
#  x: 0 
#  y: 13.5
#  z: 0.5
#  heading: -1.57079

#uav2:
#  id: 2
#  x: 4
#  y: 13.5
#  z: 0.5
#  heading: -1.57079

#uav3:
#  id: 3
#  x: -4
#  y: 13.5
#  z: 0.5
#  heading: -1.57079

# 5th layout -> Separated Start 1
#uav1:
#  id: 1
#  x: -12 
#  y: 0
#  z: 0.5
#  heading: 0

#uav2:
#  id: 2
#  x: 0
#  y: 13.5
#  z: 0.5
#  heading: -1.57079

#uav3:
#  id: 3
#  x: 12
#  y: 0
#  z: 0.5
#  heading: 3.14159

# 6th layout -> Separated Start 2
#uav1:
#  id: 1
#  x: -12 
#  y: 0
#  z: 0.5
#  heading: 0

#uav2:
#  id: 2
#  x: 0
#  y: -13.5
#  z: 0.5
#  heading: 1.57079

#uav3:
#  id: 3
#  x: 12
#  y: 0
#  z: 0.5
#  heading: 3.14159

# 7th layout -> Separated Start 3
#uav1:
#  id: 1
#  x: -12 
#  y: 0
#  z: 0.5
#  heading: 0

#uav2:
#  id: 2
#  x: 0
#  y: -13.5
#  z: 0.5
#  heading: 1.57079

#uav3:
#  id: 3
#  x: 0
#  y: 13.5
#  z: 0.5
#  heading: -1.57079

# 8th layout -> Separated Start 4
#uav1:
#  id: 1
#  x: 12 
#  y: 0
#  z: 0.5
#  heading: 3.14159

#uav2:
#  id: 2
#  x: 0
#  y: -13.5
#  z: 0.5
#  heading: 1.57079

#uav3:
#  id: 3
#  x: 0
#  y: 13.5
#  z: 0.5
#  heading: -1.57079


####################################################################################
############################ SCHOOL ################################################
####################################################################################
# 1st layout -> Joint Start 1 #(Done 2x (06/08, 16/08) NBVP, Done 2x (15/08, 16/08) AEP)
#uav1:
#  id: 1
#  x: -22 
#  y: 0
#  z: 0.5
#  heading: 0

#uav2:
#  id: 2
#  x: -22
#  y: 4
#  z: 0.5
#  heading: 0

#uav3:
#  id: 3
#  x: -22
#  y: -4
#  z: 0.5
#  heading: 0

# 2st layout -> Joint Start 2 #(Done 1x (07/08) NBVP, Done 1x (16/08) AEP)
#uav1:
#  id: 1
#  x: 22 
#  y: 0
#  z: 0.5
#  heading: 3.14159

#uav2:
#  id: 2
#  x: 22
#  y: 4
#  z: 0.5
#  heading: 3.14159

#uav3:
#  id: 3
#  x: 22
#  y: -4
#  z: 0.5
#  heading: 3.14159

# 3rd layout -> Joint Start 3 #(Done 1x (08/08) NBVP, Done 1x (17/08) AEP)
#uav1:
#  id: 1
#  x: 0 
#  y: -17
#  z: 0.5
#  heading: 1.57079

#uav2:
#  id: 2
#  x: 4
#  y: -17
#  z: 0.5
#  heading: 1.57079

#uav3:
#  id: 3
#  x: -4
#  y: -17
#  z: 0.5
#  heading: 1.57079

# 4th layout -> Joint Start 4 #(Done 1x (08/08) NBVP, Done 1x (17/08) AEP)
#uav1:
#  id: 1
#  x: 0 
#  y: 12
#  z: 0.5
#  heading: -1.57079

#uav2:
#  id: 2
#  x: 4
#  y: 12
#  z: 0.5
#  heading: -1.57079

#uav3:
#  id: 3
#  x: -4
#  y: 12
#  z: 0.5
#  heading: -1.57079

# 5th layout -> Separated Start 1 #(Done 2x (05/08) NBVP, Done 2x (16/08, 17/08) AEP)
#uav1:
#  id: 1
#  x: -22 
#  y: 0
#  z: 0.5
#  heading: 0

#uav2:
#  id: 2
#  x: 0
#  y: 12
#  z: 0.5
#  heading: -1.57079

#uav3:
#  id: 3
#  x: 22
#  y: 0
#  z: 0.5
#  heading: 3.14159

# 6th layout -> Separated Start 2 #(Done 1x (16/08) NBVP, Done 1x (16/08) AEP)
#uav1:
#  id: 1
#  x: -22 
#  y: 0
#  z: 0.5
#  heading: 0

#uav2:
#  id: 2
#  x: 0
#  y: -17
#  z: 0.5
#  heading: 1.57079

#uav3:
#  id: 3
#  x: 22
#  y: 0
#  z: 0.5
#  heading: 3.14159

# 7th layout -> Separated Start 3 #(Done 1x (16/08) NBVP, Done 1x (16/08) AEP)
#uav1:
#  id: 1
#  x: -22 
#  y: 0
#  z: 0.5
#  heading: 0

#uav2:
#  id: 2
#  x: 0
#  y: -17
#  z: 0.5
#  heading: 1.57079

#uav3:
#  id: 3
#  x: 0
#  y: 12
#  z: 0.5
#  heading: -1.57079

# 8th layout -> Separated Start 4 #(Done 1x (16/08) NBVP, Done 1x (17/08) AEP)
#uav1:
#  id: 1
#  x: 22 
#  y: 0
#  z: 0.5
#  heading: 3.14159

#uav2:
#  id: 2
#  x: 0
#  y: -17
#  z: 0.5
#  heading: 1.57079

#uav3:
#  id: 3
#  x: 0
#  y: 12
#  z: 0.5
#  heading: -1.57079


##################################################################################